let car = "shubaru";
console.log("is car==`shubaru`?.i predict true.");
console.log(car == "shubaru");
let fire = "hot";
console.log("is fire ==~hot?.i predict true.");
console.log(fire == "hot");
let bus = `ashok leyland`;
console.log("Is bus=='ashok leyland'? I predict true.");
console.log(bus === "ashok leyland");
let numbers = 35;
console.log("Is number=35? I predict true");
console.log(numbers == 35);
let percentages = "75";
console.log("Is percentages=75? I predict true");
console.log(percentages == "75");
let pakistan = 'A country';
console.log("Is PAkistan = A country? I predict true");
console.log(pakistan === "A country");
let AliGrade = "A1";
console.log("is AliGrade = 'a1'? I predict False.");
console.log(AliGrade === "a1");
let Earth = `Planet`;
console.log("is Earth = 'planet'? I predict False.");
console.log(Earth === `planet`);
let houseNumber = `50`;
console.log("is houseNumber = 50? I predict False.");
console.log(houseNumber == 52);
let myTurn = 45;
console.log("is myTurn = '45'? I predict False.");
console.log(myTurn === 44);
let ALina = "I am a good student";
console.log("Is Alina == 'I am good student'? I predict False");
console.log(ALina === "I am good student");
export {};
